addSbtPlugin("com.47deg" % "sbt-microsites" % "1.3.1")
addSbtPlugin("com.codecommit" % "sbt-spiewak-sonatype" % "0.20.1")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.2.16")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.2")
addSbtPlugin("pl.project13.scala" % "sbt-jmh" % "0.4.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.4.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
